jpa:
  hibernate:
    ddl-auto: update

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/feeds?serverTimezone=UTC
    username: admin
    password: admin

feeds:
  scheduler:
    rate: 60000
  nos:
    url: http://feeds.nos.nl/nosjournaal?format=xml